pub const GUEST_REGION_SIZE: u64 = 1 << 32;
pub const TRANSACTION_FRAME_ADDRESS: u64 = 4 * GUEST_REGION_SIZE;
pub const ACCOUNT_METADATA_AREA: u64 = 5 * GUEST_REGION_SIZE;
pub const INSTRUCTION_TRACE_AREA: u64 = 6 * GUEST_REGION_SIZE;
pub const RETURN_DATA_SCRATCHPAD: u64 = 7 * GUEST_REGION_SIZE;
pub const GUEST_ACCOUNT_PAYLOAD_BASE_ADDRESS: u64 = 8 * GUEST_REGION_SIZE;
pub const GUEST_INSTRUCTION_DATA_BASE_ADDRESS: u64 = 264 * GUEST_REGION_SIZE;
pub const GUEST_INSTRUCTION_ACCOUNT_BASE_ADDRESS: u64 = 328 * GUEST_REGION_SIZE;
